# Generated by Django 6.0 on 2026-01-18 08:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("django_imdb", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CGNGData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.JSONField(help_text="The movie data from CGNG")),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when this data was last updated.",
                    ),
                ),
                (
                    "title",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cgngdata",
                        to="django_imdb.title",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Directory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(help_text="The directory", max_length=255, unique=True),
                ),
                (
                    "title",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="directories",
                        to="django_imdb.title",
                    ),
                ),
            ],
        ),
    ]
