# Generated by Django 5.2.10 on 2026-01-26 06:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("playtime", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cgngdata",
            name="lang",
            field=models.CharField(
                default="en",
                help_text="The language code used when fetching this data.",
            ),
        ),
    ]
