# Generated by Django 5.2.10 on 2026-02-06 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("django_imdb", "0001_initial"),
        ("playtime", "0002_cgngdata_lang"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cgngdata",
            name="title",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cgngdata",
                to="django_imdb.title",
            ),
        ),
        migrations.AlterField(
            model_name="directory",
            name="title",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="directories",
                to="django_imdb.title",
            ),
        ),
    ]
